# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test

# "service" is the name of this project. This will also be added to your AWS resource names.
service: pizzaApp

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}


functions:
  newOrder:
    handler: handler.newOrder  
    events:
      - httpApi:
          path: /order
          method: post
